// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI5BxkauE1KgZvwWDwjUN3jZg26Y0oyV0',
    appId: '1:483174960744:web:57925f19e0899c7f66f5dd',
    messagingSenderId: '483174960744',
    projectId: 'kbscan-rh',
    authDomain: 'kbscan-rh.firebaseapp.com',
    storageBucket: 'kbscan-rh.appspot.com',
    measurementId: 'G-XKQSR5HQZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3WCW7IMacZElWBgFwp-R_0QvbKxwhQzM',
    appId: '1:483174960744:android:ff948de4459c121966f5dd',
    messagingSenderId: '483174960744',
    projectId: 'kbscan-rh',
    storageBucket: 'kbscan-rh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQnmxbkrwQxosuHJszTje4VmonZ1hP4ZY',
    appId: '1:483174960744:ios:ac4ab98facd7121566f5dd',
    messagingSenderId: '483174960744',
    projectId: 'kbscan-rh',
    storageBucket: 'kbscan-rh.appspot.com',
    iosBundleId: 'com.example.kbscanMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQnmxbkrwQxosuHJszTje4VmonZ1hP4ZY',
    appId: '1:483174960744:ios:ac4ab98facd7121566f5dd',
    messagingSenderId: '483174960744',
    projectId: 'kbscan-rh',
    storageBucket: 'kbscan-rh.appspot.com',
    iosBundleId: 'com.example.kbscanMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI5BxkauE1KgZvwWDwjUN3jZg26Y0oyV0',
    appId: '1:483174960744:web:dbff5fd520e1edd566f5dd',
    messagingSenderId: '483174960744',
    projectId: 'kbscan-rh',
    authDomain: 'kbscan-rh.firebaseapp.com',
    storageBucket: 'kbscan-rh.appspot.com',
    measurementId: 'G-G8E8TXT3X1',
  );
}
